### ISSUE TITLE
Написать систему логирования для серверной части

### ISSUE THREAD

**Issue by Almaz-KG** [StudentDevStudio/Development-Chat#10]
Написать простенький API для логирования информации на стороне сервера.

**Comment by Almaz-KG** [comment]
Иль зачем - это делать?!
Можно же ведь Log4J использовать?!

**Comment by Vaysman** [comment]
@Almaz-KG я привел лишь пример. возможно вам и не нужна отдельная система логирования.

не стоит делать задачу ради задачи. делайте только то, что вы можете применить сейчас. пользуйтесь принципами YAGNI и KISS.

**Comment by Almaz-KG** [comment]
Система логирования нужна!
Я уже написал простенький API для логирования
