### ISSUE TITLE
При merge - я профукал момент с папкой idea, как теперь ее удалить?

### ISSUE THREAD

**Issue by StudentDevStudio** [StudentDevStudio/Development-Chat#16]
Собственно см на титульник!

Второй вопрос:
Есть проблемка: При клонировании, через Download Zip - в зип папку попадают Eclipse файлы - а это не есть хорошо. Собственно как их выпилить от туда?

**Comment by Vaysman** [comment]
поместить <имя папки> в .gitignore.
выполнить
git add .gitignore
git rm --cached <имя папки> 
git commit -m '<имя папки>  removed'
