### ISSUE TITLE
Project: Синглетон хранящий конфигурацию затрудняет тестирование всего проекта

### ISSUE THREAD

**Issue by Vaysman** [StudentDevStudio/Development-Chat#18]
если для хранения конфигурации используется синглетон - тестировать проект становится очень сложно. 
вместо синглетон лучше использовать механизм dependency injection.

**Comment by iauglov** [comment]
@Vaysman конфигуратор видимо не правильное название, предполагается что он будет загружать параметры скажем такие как порт и файл где хранятся пользователи и отдавать их кому нужно

**Comment by Vaysman** [comment]
@iauglov синглетон всегда затрудняет тестирование. какую бы функцию он не выполнял. если вы исключите его из своего инструментария будет только лучше.

**Comment by Vaysman** [comment]
синглетон я убрал. по этому закрываю эту issue.
