### ISSUE TITLE
Нечитаемые комментарии

### ISSUE THREAD

**Issue by Vaysman** [StudentDevStudio/Development-Chat#2]
Комментарии по-русски написаны в нечитаемой кодировке (предположительно Win-1251).
Лучше использовать английские комментарии или кодировку UTF-8.

**Comment by StudentDevStudio** [comment]
Спасибо за отзыв. Щас исправим.

**Comment by Vaysman** [comment]
@StudentDevStudio лучше отвечать от своего имени, а не от имени организации. Если проблема (issue) исправлена - ее нужно закрыть.
