### ISSUE TITLE
JUnit

### ISSUE THREAD

**Issue by Vaysman** [StudentDevStudio/Development-Chat#3]
По каким соображениям выбран JUnit 3.8? Почему не 4?

**Comment by Almaz-KG** [comment]
Просто, у меня он как дефолтный в Eclipse стоял

**Comment by Vaysman** [comment]
@Almaz-KG стоит обновить! а то это прошлый век какой-то!

**Comment by Almaz-KG** [comment]
Ок, обновлю, без проблем

**Comment by Vaysman** [comment]
@Almaz-KG просто обновить мало! его надо использовать.

**Comment by StudentDevStudio** [comment]
В этом коммите JUnit обновлен до версии 4.1
