### ISSUE TITLE
Project: Проблема с коммитом

### ISSUE THREAD

**Issue by Almaz-KG** [StudentDevStudio/Development-Chat#30]
Я не знаю почему, но мой Eclipse с гитом творят чудеса. В последнем коммите не попали важные файлы в коммит. Самое страшное, что ни Eclipse, ни Git даже не предупредили об этом.

**Comment by Vaysman** [comment]
@Almaz-KG используйте гит на прямую - в командной строке. это позволяет полностью контролировать как, когда и куда попадут файлы.

**Comment by Almaz-KG** [comment]
@Vaysman к сожаления пока я так не умею, поскольку я с ним до этого не связывался

**Comment by Vaysman** [comment]
@Almaz-KG там не сложно. всего несколько команд:
- add
- rm 
- status
- commit
- checkout
- push
- pull

**Comment by Almaz-KG** [comment]
спасибо :)
