### ISSUE TITLE
JTatto не попал в maven сборку, печаль беда

### ISSUE THREAD

**Issue by Almaz-KG** [StudentDevStudio/Development-Chat#4]

**Comment by Vaysman** [comment]
интерфейс дело десятое. его всегда можно нарисовать.

**Comment by Almaz-KG** [comment]
Пока, его реализовывать проще)

**Comment by Vaysman** [comment]
@Almaz-KG потом его все равно переделывать.

**Comment by Vaysman** [comment]
@Almaz-KG и если чат будет на веб-сокетах, то интерфейсом скорей всего будет браузер и все, что сейчас сделано не пригодится.

**Comment by Almaz-KG** [comment]
Ooooooops!

**Comment by StudentDevStudio** [comment]
В этом коммите эту проблему исправил
