### ISSUE TITLE
Серверная часть

### ISSUE THREAD

**Issue by StudentDevStudio** [StudentDevStudio/Development-Chat#5]
Кто может взять и написать серверную часть?

Серверную часть - я предлагаю разделить на 2 части. 
Server на стандартных сокетах и на сервер WebSocket
Это будет 2 подпроекта.

StandartServer - на 81 порту
WebSocketServer - на 80 порту.

**Comment by Vaysman** [comment]
не правильно оформлена issue. это не задача, а что-то аморфное.
правильный вариант:
- написать подсистему persistence для сообщений
- написать подсистему логирования

и т.д.

одна задача - одно issue

**Comment by Almaz-KG** [comment]
Ок, щас переделаю
