### ISSUE TITLE
слишком большие коммиты

### ISSUE THREAD

**Issue by Vaysman** [StudentDevStudio/Development-Chat#6]
коммиты должны быть меньше. и не должны затрагивать файлы в разных частях проекта.
одна функция (функциональность) - один коммит.
тесты отдельный коммит.
в принципе один метод - один коммит.

**Comment by Almaz-KG** [comment]
Не слишком часто?

Ок, учту!

**Comment by Vaysman** [comment]
@Almaz-KG, вот когда будите мержит (merge) скажите спасибо!
